### ISSUE TITLE
[1.11.2] Tails Vanish with Mo'Bends mod

### ISSUE THREAD

**Issue by NovaViper** [kihira/Tails#83] opened 2017-06-10 02:06 UTC
It makes the tails, muzzles, ears, wings from this mod disappear off my character whenever animations are enabled. It occurs in 1.11.2 with the beta build. I

**Comment by kihira** [comment] 2017-06-10 09:46
Known issue, duplicate of #68

This is due to Mo'Bends replacing the player renderer with their own implementation

**Closed by kihira** 2017-06-10 09:46 UTC
